# ~200 major US equity tickers (S&P 100 + popular stocks)
TICKER_MAP = {
    "AAPL": "Apple",
    "ABBV": "AbbVie",
    "ABT": "Abbott Laboratories",
    "ACN": "Accenture",
    "ADBE": "Adobe",
    "ADI": "Analog Devices",
    "ADP": "Automatic Data Processing",
    "ADSK": "Autodesk",
    "AEP": "American Electric Power",
    "AFL": "Aflac",
    "AMAT": "Applied Materials",
    "AMD": "Advanced Micro Devices",
    "AMGN": "Amgen",
    "AMZN": "Amazon",
    "ANET": "Arista Networks",
    "AVGO": "Broadcom",
    "AXP": "American Express",
    "BA": "Boeing",
    "BAC": "Bank of America",
    "BK": "Bank of New York Mellon",
    "BKNG": "Booking Holdings",
    "BLK": "BlackRock",
    "BMY": "Bristol-Myers Squibb",
    "BRK.B": "Berkshire Hathaway",
    "CAT": "Caterpillar",
    "CHTR": "Charter Communications",
    "CI": "Cigna",
    "CL": "Colgate-Palmolive",
    "CMCSA": "Comcast",
    "COF": "Capital One",
    "COP": "ConocoPhillips",
    "COST": "Costco",
    "CRM": "Salesforce",
    "CRWD": "CrowdStrike",
    "CSCO": "Cisco",
    "CTAS": "Cintas",
    "CVS": "CVS Health",
    "CVX": "Chevron",
    "DASH": "DoorDash",
    "DE": "Deere",
    "DHR": "Danaher",
    "DIS": "Disney",
    "DKNG": "DraftKings",
    "DOW": "Dow Inc",
    "DUK": "Duke Energy",
    "EA": "Electronic Arts",
    "EBAY": "eBay",
    "EMR": "Emerson Electric",
    "ENPH": "Enphase Energy",
    "EXC": "Exelon",
    "F": "Ford",
    "FDX": "FedEx",
    "FSLR": "First Solar",
    "GD": "General Dynamics",
    "GE": "GE Aerospace",
    "GILD": "Gilead Sciences",
    "GM": "General Motors",
    "GOOG": "Alphabet",
    "GOOGL": "Alphabet",
    "GS": "Goldman Sachs",
    "HD": "Home Depot",
    "HON": "Honeywell",
    "IBM": "IBM",
    "ICE": "Intercontinental Exchange",
    "INTC": "Intel",
    "INTU": "Intuit",
    "ISRG": "Intuitive Surgical",
    "JNJ": "Johnson & Johnson",
    "JPM": "JPMorgan Chase",
    "KHC": "Kraft Heinz",
    "KO": "Coca-Cola",
    "LIN": "Linde",
    "LLY": "Eli Lilly",
    "LMT": "Lockheed Martin",
    "LOW": "Lowe's",
    "LRCX": "Lam Research",
    "LULU": "Lululemon",
    "MA": "Mastercard",
    "MAR": "Marriott",
    "MCD": "McDonald's",
    "MCHP": "Microchip Technology",
    "MDLZ": "Mondelez",
    "MDT": "Medtronic",
    "MET": "MetLife",
    "META": "Meta Platforms",
    "MMM": "3M",
    "MO": "Altria",
    "MRK": "Merck",
    "MRNA": "Moderna",
    "MS": "Morgan Stanley",
    "MSFT": "Microsoft",
    "MU": "Micron Technology",
    "NEE": "NextEra Energy",
    "NFLX": "Netflix",
    "NKE": "Nike",
    "NOC": "Northrop Grumman",
    "NOW": "ServiceNow",
    "NVDA": "Nvidia",
    "ORCL": "Oracle",
    "OXY": "Occidental Petroleum",
    "PANW": "Palo Alto Networks",
    "PEP": "PepsiCo",
    "PFE": "Pfizer",
    "PG": "Procter & Gamble",
    "PLTR": "Palantir",
    "PM": "Philip Morris",
    "PNC": "PNC Financial",
    "PYPL": "PayPal",
    "QCOM": "Qualcomm",
    "REGN": "Regeneron",
    "RIVN": "Rivian",
    "ROKU": "Roku",
    "RTX": "RTX Corporation",
    "SBUX": "Starbucks",
    "SCHW": "Charles Schwab",
    "SHOP": "Shopify",
    "SLB": "Schlumberger",
    "SMCI": "Super Micro Computer",
    "SNAP": "Snap",
    "SNPS": "Synopsys",
    "SO": "Southern Company",
    "SOFI": "SoFi Technologies",
    "SPG": "Simon Property Group",
    "SPGI": "S&P Global",
    "SQ": "Block",
    "SYK": "Stryker",
    "T": "AT&T",
    "TGT": "Target",
    "TJX": "TJX Companies",
    "TMO": "Thermo Fisher",
    "TMUS": "T-Mobile",
    "TSLA": "Tesla",
    "TSM": "Taiwan Semiconductor",
    "TXN": "Texas Instruments",
    "UNH": "UnitedHealth",
    "UNP": "Union Pacific",
    "UPS": "UPS",
    "UBER": "Uber",
    "USB": "US Bancorp",
    "V": "Visa",
    "VLO": "Valero Energy",
    "VMW": "VMware",
    "VZ": "Verizon",
    "WBA": "Walgreens",
    "WFC": "Wells Fargo",
    "WM": "Waste Management",
    "WMT": "Walmart",
    "XOM": "ExxonMobil",
    "ZM": "Zoom Video",
    "ZS": "Zscaler",
    # Additional popular / high-interest tickers
    "ABNB": "Airbnb",
    "AI": "C3.ai",
    "ALB": "Albemarle",
    "ALGN": "Align Technology",
    "ALLY": "Ally Financial",
    "AMC": "AMC Entertainment",
    "APD": "Air Products",
    "APP": "AppLovin",
    "ARM": "Arm Holdings",
    "ASML": "ASML",
    "AZN": "AstraZeneca",
    "BB": "BlackBerry",
    "BILL": "BILL Holdings",
    "BIRK": "Birkenstock",
    "BX": "Blackstone",
    "CARR": "Carrier Global",
    "CCL": "Carnival",
    "CELH": "Celsius Holdings",
    "CFLT": "Confluent",
    "COIN": "Coinbase",
    "CPRT": "Copart",
    "DDOG": "Datadog",
    "DELL": "Dell Technologies",
    "DLO": "DLocal",
    "DUOL": "Duolingo",
    "DXCM": "DexCom",
    "ELF": "e.l.f. Beauty",
    "FTNT": "Fortinet",
    "GME": "GameStop",
    "GRAB": "Grab Holdings",
    "HLT": "Hilton",
    "HPE": "Hewlett Packard Enterprise",
    "HPQ": "HP Inc",
    "IONQ": "IonQ",
    "KLAC": "KLA Corporation",
    "KKR": "KKR",
    "LCID": "Lucid Group",
    "LI": "Li Auto",
    "MARA": "Marathon Digital",
    "MELI": "MercadoLibre",
    "MPC": "Marathon Petroleum",
    "MRVL": "Marvell Technology",
    "NET": "Cloudflare",
    "NIO": "NIO",
    "NTES": "NetEase",
    "ON": "ON Semiconductor",
    "OPEN": "Opendoor",
    "PARA": "Paramount Global",
    "PATH": "UiPath",
    "PINS": "Pinterest",
    "PSX": "Phillips 66",
    "RBLX": "Roblox",
    "SE": "Sea Limited",
    "SNOW": "Snowflake",
    "SPOT": "Spotify",
    "SYF": "Synchrony Financial",
    "TFC": "Truist Financial",
    "TTWO": "Take-Two Interactive",
    "TTD": "The Trade Desk",
    "TWLO": "Twilio",
    "TTE": "TotalEnergies",
    "U": "Unity Software",
    "UAL": "United Airlines",
    "UPST": "Upstart",
    "W": "Wayfair",
    "WDAY": "Workday",
    "XEL": "Xcel Energy",
    "XPEV": "XPeng",
    "ZI": "ZoomInfo",
}

# Ambiguous tickers to skip during uppercase-word matching
# (only match these via $CASHTAG or company name)
AMBIGUOUS_TICKERS = {
    "A", "AI", "AM", "AN", "ALL", "ARE", "BA", "BB", "BIG",
    "C", "CL", "CI", "DE", "DO", "EA", "F", "GE", "GO",
    "HAS", "IT", "K", "KEY", "L", "LI", "LOW", "MA", "MET",
    "MO", "MS", "NET", "NOW", "ON", "OPEN", "OR", "RE",
    "SE", "SO", "SQ", "T", "U", "V", "W", "WAR", "WE",
    "DOW", "ICE", "ARM", "PATH", "SNAP", "DASH", "COIN",
    "ALLY", "GRAB", "APP", "BILL",
}
